[package]
name = "pretty-print"
version = "0.1.0"
authors = ["A.J. Roetker <ajroetker@gmail.com>"]

[dependencies]
docopt = "0.6.*"
serde = "0.7.*"
serde_json = "0.7.*"
rustc-serialize = "0.3.*"
hyper = "0.7.*"
openssl = "*"
